#!/usr/bin/env python3
"""
Replace config_webview_packages.xml inside framework-res.apk
to add Chrome as a WebView provider on Android 7.

Usage:
    python patch_framework_res.py framework-res.apk config_webview_packages_patched.bin [output.apk]
    python patch_framework_res.py --check framework-res.apk

Output:
    framework-res-patched.apk (or specified output path)
"""
import zipfile
import sys
import os

def check_config_size(apk_path):
    """Print the size of config_webview_packages.xml inside the APK."""
    if not os.path.exists(apk_path):
        print("0")
        return
    try:
        with zipfile.ZipFile(apk_path, 'r') as z:
            info = z.getinfo('res/xml/config_webview_packages.xml')
            print(info.file_size)
    except (KeyError, Exception):
        print("0")

def main():
    if len(sys.argv) >= 3 and sys.argv[1] == '--check':
        check_config_size(sys.argv[2])
        return

    if len(sys.argv) < 3:
        print("Usage: python patch_framework_res.py <framework-res.apk> <patched_xml.bin> [output.apk]")
        print("       python patch_framework_res.py --check <framework-res.apk>")
        print()
        print("  framework-res.apk    : pulled from /system/framework/framework-res.apk")
        print("  patched_xml.bin      : generated by patch_webview_config.py")
        sys.exit(1)

    apk_path = sys.argv[1]
    patch_path = sys.argv[2]
    output_path = sys.argv[3] if len(sys.argv) >= 4 else os.path.splitext(apk_path)[0] + '-patched.apk'

    if not os.path.exists(apk_path):
        print(f"Error: {apk_path} not found")
        sys.exit(1)
    if not os.path.exists(patch_path):
        print(f"Error: {patch_path} not found")
        sys.exit(1)

    with open(patch_path, 'rb') as f:
        patched_data = f.read()

    target_entry = 'res/xml/config_webview_packages.xml'
    replaced = False

    with zipfile.ZipFile(apk_path, 'r') as zin:
        with zipfile.ZipFile(output_path, 'w') as zout:
            for item in zin.infolist():
                if item.filename == target_entry:
                    zout.writestr(item, patched_data)
                    replaced = True
                    print(f"  REPLACED: {item.filename}")
                    print(f"    original size: {item.file_size} bytes")
                    print(f"    patched size:  {len(patched_data)} bytes")
                else:
                    data = zin.read(item.filename)
                    zout.writestr(item, data)

    if not replaced:
        print(f"Error: {target_entry} not found in {apk_path}")
        os.remove(output_path)
        sys.exit(1)

    orig_size = os.path.getsize(apk_path)
    new_size = os.path.getsize(output_path)
    print(f"\nOriginal APK: {orig_size:,} bytes")
    print(f"Patched APK:  {new_size:,} bytes")
    print(f"Output: {output_path}")
    print("\nNext steps:")
    print(f"  adb push {output_path} /sdcard/")
    print(f"  adb shell cp /sdcard/{os.path.basename(output_path)} /system/framework/framework-res.apk")
    print(f"  adb shell chmod 644 /system/framework/framework-res.apk")
    print(f"  adb shell settings put global webview_provider com.android.chrome")
    print(f"  adb reboot")

if __name__ == '__main__':
    main()
